def get_languages_list
    puts "Afrikaans -> af"
    puts "Albanian -> sq"
    puts "Amharic -> am"
    puts "Arabic -> ar"
    puts "Armenian -> hy"
    puts "Azerbaijani -> az"
    puts "Basque -> eu"
    puts "Belarusian -> be"
    puts "Bengali -> bn"
    puts "Bosnian -> bs"
    puts "Bulgarian -> bg"
    puts "Catalan -> ca"
    puts "Cebuano -> ceb"
    puts "Chinese (Simplified) -> zh-CN"
    puts "Chinese (Traditional)-> zh-TW"
    puts "Corsican -> co"
    puts "Croatian -> hr"
    puts "Czech -> cs"
    puts "Danish -> da"
    puts "Dutch -> nl"
    puts "English -> en"
    puts "Esperanto -> eo"
    puts "Estonian -> et"
    puts "Finnish -> fi"
    puts "French -> fr"
    puts "Frisian -> fy"
    puts "Galician -> gl"
    puts "Georgian -> ka"
    puts "German -> de"
    puts "Greek -> el"
    puts "Gujarati -> gu"
    puts "Haitian Creole -> ht"
    puts "Hausa -> ha"
    puts "Hawaiian -> haw"
    puts "Hebrew -> he"
    puts "Hindi -> hi"
    puts "Hmong -> hmn"
    puts "Hungarian -> hu"
    puts "Icelandic -> is"
    puts "Igbo -> ig"
    puts "Indonesian -> id"
    puts "Irish -> ga"
    puts "Italian -> it"
    puts "Japanese -> ja"
    puts "Javanese -> jw"
    puts "Kannada -> kn"
    puts "Kazakh -> kk"
    puts "Khmer -> km"
    puts "Korean -> ko"
    puts "Kurdish -> ku"
    puts "Kyrgyz -> ky"
    puts "Lao -> lo"
    puts "Latin -> la"
    puts "Latvian -> lv"
    puts "Lithuanian -> lt"
    puts "Luxembourgish -> lb"
    puts "Macedonian -> mk"
    puts "Malagasy -> mg"
    puts "Malay -> ms"
    puts "Malayalam -> ml"
    puts "Maltese -> mt"
    puts "Maori -> mi"
    puts "Marathi -> mr"
    puts "Mongolian -> mn"
    puts "Myanmar (Burmese) -> my"
    puts "Nepali -> ne"
    puts "Norwegian -> no"
    puts "Nyanja (Chichewa) -> ny"
    puts "Pashto -> ps"
    puts "Persian -> fa"
    puts "Polish -> pl"
    puts "Portuguese (Portugal, Brazil) -> pt"
    puts "Punjabi -> pa"
    puts "Romanian -> ro"
    puts "Russian -> ru"
    puts "Samoan -> sm"
    puts "Scots Gaelic -> gd"
    puts "Serbian -> sr"
    puts "Sesotho -> st"
    puts "Shona -> sn"
    puts "Sindhi -> sd"
    puts "Sinhala (Sinhalese) -> si"
    puts "Slovak -> sk"
    puts "Slovenian -> sl"
    puts "Somali -> so"
    puts "Spanish -> es"
    puts "Sundanese -> su"
    puts "Swahili -> sw"
    puts "Swedish -> sv"
    puts "Tagalog (Filipino) -> tl"
    puts "Tajik -> tg"
    puts "Tamil -> ta"
    puts "Telugu -> te"
    puts "Thai -> th"
    puts "Turkish -> tr"
    puts "Ukrainian -> uk"
    puts "Urdu -> ur"
    puts "Uzbek -> uz"
    puts "Vietnamese -> vi"
    puts "Welsh -> cy"
    puts "Xhosa -> xh"
    puts "Yiddish -> yi"
    puts "Yoruba -> yo"
    puts "Zulu -> zu"
end